services:
  smartinvest-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: smartinvest-db
    restart: always
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: ${DB_PASSWORD}
      MSSQL_PID: 'Developer'
      MSSQL_TCP_PORT: 1433
    ports:
      - "5434:1433"
    networks:
      - backend

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    restart: always
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN_USER}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HEALTH_ENABLED: "true"
      KC_LOG_LEVEL: info
    command: ["start-dev", "--http-port", "7080", "--import-realm"]
    volumes:
      - ./docker/keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    ports:
      - "7080:7080"
    networks:
      - backend

  app:
    build: .
    container_name: smartinvest-api
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      smartinvest-db:
        condition: service_healthy
      keycloak:
          condition: service_healthy
    networks:
      - backend

networks:
  backend:
    driver: bridge
