services:
  smartinvest-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: smartinvest-db
    restart: always
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: ${DB_PASSWORD}
      MSSQL_PID: 'Developer'
      MSSQL_TCP_PORT: 1433
    ports:
      - "5434:1433"
    networks:
      - backend

  app:
    build: .
    container_name: smartinvest-api
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - smartinvest-db
    networks:
      - backend

networks:
  backend:
    driver: bridge
